import type { ReactElement } from 'react'
import { Link } from 'react-router-dom'
import styles from '../whoops-hoops.module.css'

const LAST_UPDATED = 'April 27, 2026'
const SUPPORT_EMAIL = 'leon.cheng.work@gmail.com'

export default function PrivacyRoute(): ReactElement {
  return (
    <div className={styles.page}>
      <main className={styles.content}>
        <header className={styles.pageHeader}>
          <h1>Whoops Hoops &mdash; Privacy Policy</h1>
          <p className={styles.lastUpdated}>Last updated: {LAST_UPDATED}</p>
        </header>
        <section className={styles.body}>
          <p>
            Whoops Hoops (&ldquo;the App&rdquo;) is a daily NBA player guessing game published by
            Leon Cheng (&ldquo;we&rdquo;, &ldquo;us&rdquo;). This Privacy Policy explains what
            information the App collects, how it is used, and the choices you have.
          </p>
          <p>
            The App is designed to be playable without an account and without sharing personal
            information. We do not require sign-in, do not run advertisements, and do not sell or
            share your data with third parties for advertising or marketing.
          </p>

          <h2>Information we collect</h2>
          <p>
            We use Google Firebase Analytics to understand how the App is used so we can improve
            it. Firebase Analytics is configured with Apple&rsquo;s Identifier for Advertisers
            (IDFA) collection disabled. The data we collect through Firebase Analytics is limited
            to:
          </p>
          <ul>
            <li>
              <strong>Device identifiers</strong> &mdash; an app-instance ID generated by Firebase
              and basic device information (device model, iOS version, language, region).
            </li>
            <li>
              <strong>Product interaction</strong> &mdash; aggregated, in-app events such as game
              starts, guesses, wins, streaks, and screen views, used to understand feature usage
              and fix issues.
            </li>
            <li>
              <strong>Crash data</strong> &mdash; if the App crashes, we collect a diagnostic crash
              report (stack trace, device model, iOS version, app version) so we can fix the bug.
            </li>
          </ul>
          <p>
            We do <strong>not</strong> collect your name, email address, phone number, contacts,
            photos, location, or any health, financial, or biometric information. We do not use
            tracking technologies that would link your activity in this App to your identity in
            other apps or websites.
          </p>

          <h2>How we use information</h2>
          <ul>
            <li>To operate, maintain, and improve the App.</li>
            <li>To diagnose and fix crashes and bugs.</li>
            <li>To understand which features are used and how to make them better.</li>
          </ul>

          <h2>Local storage on your device</h2>
          <p>
            Some game state &mdash; for example your current streak, recent guesses, and
            preferences &mdash; is stored locally on your device. Deleting the App removes this
            local data.
          </p>

          <h2>Push notifications</h2>
          <p>
            The App may ask permission to send local reminder notifications (for example, a daily
            puzzle reminder). You can grant or deny this permission when prompted, and you can
            change it at any time in{' '}
            <em>Settings &rsaquo; Notifications &rsaquo; Whoops Hoops</em> on your device.
          </p>

          <h2>NBA player data</h2>
          <p>
            The App displays publicly available NBA player names and basic statistics for the
            purposes of the game. The App is not affiliated with, endorsed by, or sponsored by the
            NBA or any team.
          </p>

          <h2>Children&rsquo;s privacy</h2>
          <p>
            The App is rated 4+ and does not knowingly collect personal information from children.
            If you believe a child has provided us with personal information, please contact us and
            we will delete it.
          </p>

          <h2>Data retention</h2>
          <p>
            Analytics and crash data are retained by Google Firebase under its standard retention
            settings. We do not maintain a separate user database for the App.
          </p>

          <h2>Your choices</h2>
          <ul>
            <li>You can deny or revoke notification permission in your device settings.</li>
            <li>
              You can stop all data collection by uninstalling the App. This will also remove
              locally stored game state.
            </li>
          </ul>

          <h2>Changes to this policy</h2>
          <p>
            We may update this Privacy Policy from time to time. When we do, we will update the
            &ldquo;Last updated&rdquo; date above. Material changes will also be reflected in the
            App&rsquo;s release notes.
          </p>

          <h2>Contact</h2>
          <div className={styles.contactCard}>
            <p>
              Questions about this policy? Email{' '}
              <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
            </p>
            <p>
              See also our{' '}
              <Link to="/apps/whoops-hoops/support">Whoops Hoops support page</Link>.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}
