import type { NextPage } from "next";
import Head from "next/head";
import Copyright from "../components/copyright/copyright";
import Experiences from "../components/experiences/experiences";
import Headline from "../components/headline/headline";
import Social from "../components/social/social";
import styles from "./Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leon's Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />{" "}
      </Head>

      <main>
        <Headline />
        <hr />
        <Social />
        <hr />
        <Experiences />

        <Copyright />
      </main>
    </div>
  );
};

export default Home;
