import type { NextPage } from "next";
import Head from "next/head";
import Copyright from "../components/copyright/copyright";
import Experiences from "../components/experiences/experiences";
import Headline from "../components/headline/headline";
import Social from "../components/social/social";
import styles from "./Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leon&#39;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main>
        <Headline />
        <hr />
        <Social />
        <hr />
        <Experiences />
        <Copyright />
      </main>
    </div>
  );
};

export default Home;
